---
# tasks file for ansible-suricata
- ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.import_tasks: configure_suricata.yml
  when: config_suricata is defined and config_suricata

- ansible.builtin.import_tasks: configure_interface_offloading.yml
  when: suricata_interfaces | selectattr('disable_offloading') | length > 0
